name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Build with Maven
        run: mvn clean install

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "target/*.jar"
          target: "~/app"

      - name: SSH EC2 and restart app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            pkill -f 'java'
            nohup java -jar ~/app/*.jar > nohup.out 2>&1 &

      - name: Set up SSH Key
        run: |
          echo "$EC2_SSH_KEY" > ec2-key.pem
          chmod 600 ec2-key.pem
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
