name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest


    # 환경변수 전역 설정 (workflow 내 모든 steps에서 사용 가능)
    env:
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

    steps:
      - name: Git clone
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ubuntu
          key: ${{ env.EC2_SSH_KEY }}
          source: "target/*.jar"
          target: "~/app"

      - name: SSH EC2 and restart app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ubuntu
          key: ${{ env.EC2_SSH_KEY }}
          timeout: 600
          script: |
            mkdir -p ~/app
            pkill -f 'java' || true
            cd ~/app
            nohup java -Dspring.datasource.username=${MYSQL_USER} \
                       -Dspring.datasource.password=${MYSQL_ROOT_PASSWORD} \
                       -Dspring.datasource.url=jdbc:mysql://localhost:3306/${MYSQL_DATABASE} \
                       -jar *.jar > nohup.out 2>&1 &